#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
mkdir -p logs data
# Keep previous custom values unless duplicated keys exist; rewrite v52 block.
cp .env .env.bak.v52.$(date +%Y%m%d_%H%M%S) 2>/dev/null || true
for k in \
  V52_CATEGORY V52_MARGIN_COIN V52_MARGIN_MODE V52_LEVERAGE V52_DRY_RUN V52_LIVE_ENABLED V52_LIVE_CONFIRM \
  V52_LOOP_SECONDS V52_CANDLE_REFRESH_SECONDS V52_UNIVERSE_COUNT V52_MAX_ACTIVE_SYMBOLS V52_MAX_OPEN_POSITIONS \
  V52_TOTAL_CAPITAL_RATIO V52_PER_ORDER_CAPITAL_RATIO_CAP V52_MAX_ORDER_NOTIONAL_USDT \
  V52_VWAP_WINDOW_MINUTES V52_WARMUP_MINUTES V52_BAND_STD_MULT V52_ADX_PERIOD V52_ADX_MAX \
  V52_TP_PCT V52_SL_PCT V52_SHOCK_WINDOW_SECONDS V52_SHOCK_PCT V52_SHOCK_COOLDOWN_MINUTES \
  V52_DAILY_GUARD_ENABLED V52_DAILY_TARGET_PCT V52_DAILY_LOSS_PCT V52_MAX_TRADES_PER_DAY V52_NOTIFY_EVERY_MINUTES V52_NOTIFY_ACTIONS_ONLY \
  V52_FILL_NOTIFY_ENABLED V52_FILL_LOOKBACK_MINUTES V52_NOTIFY_ALL_FILLS \
  V52_USE_COINGECKO V52_STATE_PATH V52_JSONL_PATH V52_SYMBOLS; do
  sed -i "/^${k}=/d" .env 2>/dev/null || true
done
cat >> .env <<'EOF'

# ===== v5.2 Top10 VWAP Rubber Band Scalp =====
# Video-derived VWAP strategy: ADX<=20 range filter, VWAP bands, maker limit entries,
# TP 0.6%, SL 0.3%, VWAP touch exit, 5s shock cooldown.
V52_CATEGORY=USDT-FUTURES
V52_MARGIN_COIN=USDT
V52_MARGIN_MODE=crossed
V52_LEVERAGE=1
V52_TOTAL_CAPITAL_RATIO=0.30
V52_PER_ORDER_CAPITAL_RATIO_CAP=0.003
V52_MAX_ORDER_NOTIONAL_USDT=200

# Live gate. Set true/confirm only when you intentionally run live.
V52_DRY_RUN=false
V52_LIVE_ENABLED=true
V52_LIVE_CONFIRM=START_V52_VWAP_LIVE

V52_LOOP_SECONDS=10
V52_CANDLE_REFRESH_SECONDS=60
V52_UNIVERSE_COUNT=10
V52_MAX_ACTIVE_SYMBOLS=10
V52_MAX_OPEN_POSITIONS=3
V52_USE_COINGECKO=true

V52_VWAP_WINDOW_MINUTES=180
V52_WARMUP_MINUTES=10
V52_BAND_STD_MULT=2.0
V52_ADX_PERIOD=14
V52_ADX_MAX=20

V52_TP_PCT=0.006
V52_SL_PCT=0.003
V52_SHOCK_WINDOW_SECONDS=5
V52_SHOCK_PCT=0.15
V52_SHOCK_COOLDOWN_MINUTES=10

V52_DAILY_GUARD_ENABLED=false
V52_DAILY_TARGET_PCT=999.0
V52_DAILY_LOSS_PCT=999.0
V52_MAX_TRADES_PER_DAY=200
V52_NOTIFY_EVERY_MINUTES=30
V52_NOTIFY_ACTIONS_ONLY=true
V52_FILL_NOTIFY_ENABLED=true
V52_FILL_LOOKBACK_MINUTES=180
V52_NOTIFY_ALL_FILLS=true
V52_STATE_PATH=data/v52_vwap_top10_state.json
V52_JSONL_PATH=data/v52_vwap_top10_events.jsonl
EOF
chmod +x run_v52_vwap_preflight.sh run_v52_vwap_universe.sh run_v52_vwap_once.sh start_v52_vwap_live.sh stop_v52_vwap.sh status_v52_vwap.sh view_v52_vwap_log.sh cancel_v52_vwap_orders.sh 2>/dev/null || true
echo "✅ v5.2 Top10 VWAP Rubber Band Scalp live patch applied."
echo "실전 가능 버전입니다. 반드시 preflight/universe/once 확인 후 start 하세요."
